### ISSUE TITLE
ImportError: cannot import name api

### ISSUE THREAD

**Issue by renbanford** [reincubate/deviceidentifier-py#1]
Hi all, when trying to import the module, I get the following error, any pointers? Running Python 2.7.15 and am following the documentation [here](https://docs.reincubate.com/deviceidentifier/quickstart/)

```
Traceback (most recent call last):
  File "deviceidentifier.py", line 1, in <module>
    from deviceidentifier import api
  File "/Users/benranford/x/x/x/deviceidentifier.py", line 1, in <module>
    from deviceidentifier import api
ImportError: cannot import name api
```

**Comment by renbanford** [comment]
Seems to be working with the github version, the pip version seems to be broken. I have reinstalled multiple times.

**Comment by afit** [comment]
Hi Ben, thanks for the report. I'm afraid I can't replicate the issue you report. Here's what I did:

```bash
$ sudo pip install deviceidentifier
Collecting deviceidentifier
Requirement already satisfied: requests==2.12.4 in /Library/Python/2.7/site-packages (from deviceidentifier) (2.12.4)
Installing collected packages: deviceidentifier
Successfully installed deviceidentifier-0.0.5

$ python
Python 2.7.10 (default, Aug 17 2018, 17:41:52)
[GCC 4.2.1 Compatible Apple LLVM 10.0.0 (clang-1000.0.42)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from deviceidentifier import api
>>> api.lookup( api.TYPE_APPLE_SERIAL, 'C8QH6T96DPNG' )
{ JSON response, etc.
```

Are you able to shed any more light on this?

**Comment by chentaowhy** [comment]
> Hi all, when trying to import the module, I get the following error, any pointers? Running Python 2.7.15 and am following the documentation [here](https://docs.reincubate.com/deviceidentifier/quickstart/)
> 
> 
> 
> ```
> 
> Traceback (most recent call last):
> 
>   File "deviceidentifier.py", line 1, in <module>
> 
>     from deviceidentifier import api
> 
>   File "/Users/benranford/x/x/x/deviceidentifier.py", line 1, in <module>
> 
>     from deviceidentifier import api
> 
> ImportError: cannot import name api
> 
> ```

**Comment by hlynursmari1** [comment]
Hi @chentaowhy, are you experiencing the same issue?

Looking at the original report, it looks like the problem might be due to ambiguous import statements, i.e. the name of the module that's importing `deviceidentifier` is also called `deviceidentifier`. See [PEP 328](https://www.python.org/dev/peps/pep-0328/) for details.

The recommended fix is to impose absolute imports by adding the following to the top of the file:

```python
from __future__ import absolute_import

from deviceidentifier import api
```
